//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.BrowseGot {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameOfThronesCharacter", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GameOfThronesCharacter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FamilyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Family {
            get {
                return this.FamilyField;
            }
            set {
                if ((object.ReferenceEquals(this.FamilyField, value) != true)) {
                    this.FamilyField = value;
                    this.RaisePropertyChanged("Family");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameOfThronesContinent", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GameOfThronesContinent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BrowseGot.CharacterSearchServiceSoap")]
    public interface CharacterSearchServiceSoap {
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchCharacters", ReplyAction="*")]
        Client.BrowseGot.SearchCharactersResponse SearchCharacters(Client.BrowseGot.SearchCharactersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchCharacters", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.BrowseGot.SearchCharactersResponse> SearchCharactersAsync(Client.BrowseGot.SearchCharactersRequest request);
        
        // CODEGEN: Generating message contract since element name value from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchContinent", ReplyAction="*")]
        Client.BrowseGot.SearchContinentResponse SearchContinent(Client.BrowseGot.SearchContinentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchContinent", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.BrowseGot.SearchContinentResponse> SearchContinentAsync(Client.BrowseGot.SearchContinentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchCharactersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchCharacters", Namespace="http://tempuri.org/", Order=0)]
        public Client.BrowseGot.SearchCharactersRequestBody Body;
        
        public SearchCharactersRequest() {
        }
        
        public SearchCharactersRequest(Client.BrowseGot.SearchCharactersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchCharactersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string value;
        
        public SearchCharactersRequestBody() {
        }
        
        public SearchCharactersRequestBody(string key, string value) {
            this.key = key;
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchCharactersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchCharactersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.BrowseGot.SearchCharactersResponseBody Body;
        
        public SearchCharactersResponse() {
        }
        
        public SearchCharactersResponse(Client.BrowseGot.SearchCharactersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchCharactersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.BrowseGot.GameOfThronesCharacter[] SearchCharactersResult;
        
        public SearchCharactersResponseBody() {
        }
        
        public SearchCharactersResponseBody(Client.BrowseGot.GameOfThronesCharacter[] SearchCharactersResult) {
            this.SearchCharactersResult = SearchCharactersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchContinentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchContinent", Namespace="http://tempuri.org/", Order=0)]
        public Client.BrowseGot.SearchContinentRequestBody Body;
        
        public SearchContinentRequest() {
        }
        
        public SearchContinentRequest(Client.BrowseGot.SearchContinentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchContinentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string value;
        
        public SearchContinentRequestBody() {
        }
        
        public SearchContinentRequestBody(string value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchContinentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchContinentResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.BrowseGot.SearchContinentResponseBody Body;
        
        public SearchContinentResponse() {
        }
        
        public SearchContinentResponse(Client.BrowseGot.SearchContinentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchContinentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.BrowseGot.GameOfThronesContinent SearchContinentResult;
        
        public SearchContinentResponseBody() {
        }
        
        public SearchContinentResponseBody(Client.BrowseGot.GameOfThronesContinent SearchContinentResult) {
            this.SearchContinentResult = SearchContinentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CharacterSearchServiceSoapChannel : Client.BrowseGot.CharacterSearchServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CharacterSearchServiceSoapClient : System.ServiceModel.ClientBase<Client.BrowseGot.CharacterSearchServiceSoap>, Client.BrowseGot.CharacterSearchServiceSoap {
        
        public CharacterSearchServiceSoapClient() {
        }
        
        public CharacterSearchServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CharacterSearchServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CharacterSearchServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CharacterSearchServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.BrowseGot.SearchCharactersResponse Client.BrowseGot.CharacterSearchServiceSoap.SearchCharacters(Client.BrowseGot.SearchCharactersRequest request) {
            return base.Channel.SearchCharacters(request);
        }
        
        public Client.BrowseGot.GameOfThronesCharacter[] SearchCharacters(string key, string value) {
            Client.BrowseGot.SearchCharactersRequest inValue = new Client.BrowseGot.SearchCharactersRequest();
            inValue.Body = new Client.BrowseGot.SearchCharactersRequestBody();
            inValue.Body.key = key;
            inValue.Body.value = value;
            Client.BrowseGot.SearchCharactersResponse retVal = ((Client.BrowseGot.CharacterSearchServiceSoap)(this)).SearchCharacters(inValue);
            return retVal.Body.SearchCharactersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.BrowseGot.SearchCharactersResponse> Client.BrowseGot.CharacterSearchServiceSoap.SearchCharactersAsync(Client.BrowseGot.SearchCharactersRequest request) {
            return base.Channel.SearchCharactersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.BrowseGot.SearchCharactersResponse> SearchCharactersAsync(string key, string value) {
            Client.BrowseGot.SearchCharactersRequest inValue = new Client.BrowseGot.SearchCharactersRequest();
            inValue.Body = new Client.BrowseGot.SearchCharactersRequestBody();
            inValue.Body.key = key;
            inValue.Body.value = value;
            return ((Client.BrowseGot.CharacterSearchServiceSoap)(this)).SearchCharactersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.BrowseGot.SearchContinentResponse Client.BrowseGot.CharacterSearchServiceSoap.SearchContinent(Client.BrowseGot.SearchContinentRequest request) {
            return base.Channel.SearchContinent(request);
        }
        
        public Client.BrowseGot.GameOfThronesContinent SearchContinent(string value) {
            Client.BrowseGot.SearchContinentRequest inValue = new Client.BrowseGot.SearchContinentRequest();
            inValue.Body = new Client.BrowseGot.SearchContinentRequestBody();
            inValue.Body.value = value;
            Client.BrowseGot.SearchContinentResponse retVal = ((Client.BrowseGot.CharacterSearchServiceSoap)(this)).SearchContinent(inValue);
            return retVal.Body.SearchContinentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.BrowseGot.SearchContinentResponse> Client.BrowseGot.CharacterSearchServiceSoap.SearchContinentAsync(Client.BrowseGot.SearchContinentRequest request) {
            return base.Channel.SearchContinentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.BrowseGot.SearchContinentResponse> SearchContinentAsync(string value) {
            Client.BrowseGot.SearchContinentRequest inValue = new Client.BrowseGot.SearchContinentRequest();
            inValue.Body = new Client.BrowseGot.SearchContinentRequestBody();
            inValue.Body.value = value;
            return ((Client.BrowseGot.CharacterSearchServiceSoap)(this)).SearchContinentAsync(inValue);
        }
    }
}
